# Generated by Django 4.2.7 on 2025-12-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='classrooms',
            field=models.ManyToManyField(blank=True, related_name='students', to='attendance.classroom'),
        ),
    ]
